// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplyChainManagement.Db;

#nullable disable

namespace SupplyChainManagement.Migrations
{
    [DbContext(typeof(SCMDbContext))]
    [Migration("20241106052528_poModelUpdate")]
    partial class poModelUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupplyChainManagement.Models.DeliveryUnit", b =>
                {
                    b.Property<long>("DeliveryUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeliveryUnitId"));

                    b.Property<string>("DeliveryUnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryUnitId");

                    b.ToTable("DeliveryUnits");
                });

            modelBuilder.Entity("SupplyChainManagement.Models.Merchandiser", b =>
                {
                    b.Property<long>("MerchandiserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MerchandiserId"));

                    b.Property<string>("MerchandiserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MerchandiserId");

                    b.ToTable("Merchandisers");
                });

            modelBuilder.Entity("SupplyChainManagement.Models.PRDetails", b =>
                {
                    b.Property<long>("PRDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PRDetailsId"));

                    b.Property<int>("ItemMasterID")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadTime")
                        .HasColumnType("int");

                    b.Property<decimal>("PRQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("PurchaseRequisitionPRID")
                        .HasColumnType("bigint");

                    b.Property<long?>("PurchaseRequisitionPRID1")
                        .HasColumnType("bigint");

                    b.Property<string>("ShadeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YBookingNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRDetailsId");

                    b.HasIndex("PurchaseRequisitionPRID");

                    b.HasIndex("PurchaseRequisitionPRID1");

                    b.ToTable("ItemDetails");
                });

            modelBuilder.Entity("SupplyChainManagement.Models.PurchaseRequisition", b =>
                {
                    b.Property<long>("PRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PRID"));

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PRDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PRNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitionar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRID");

                    b.ToTable("PurchaseRequisitions");
                });

            modelBuilder.Entity("SupplyChainManagement.Models.Supplier", b =>
                {
                    b.Property<long>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SupplierId"));

                    b.Property<string>("ContactDisplayCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("SupplyChainManagement.Models.YarnPOChild", b =>
                {
                    b.Property<int>("YPOChildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YPOChildID"));

                    b.Property<string>("BookingNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HSCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ItemMasterID")
                        .HasColumnType("int");

                    b.Property<decimal>("PIValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PoQty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("ReceivedCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UnitName")
                        .HasColumnType("int");

                    b.Property<int>("YPOMasterID")
                        .HasColumnType("int");

                    b.Property<string>("YarnLotNo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("YarnShade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("YPOChildID");

                    b.ToTable("ItemPODetail");
                });

            modelBuilder.Entity("SupplyChainManagement.Models.YarnPOMaster", b =>
                {
                    b.Property<int>("YPOMasterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YPOMasterID"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Charges")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PODate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PortofDischarge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortofLoading")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("QuotationRefDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuotationRefNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShipmentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingTolerance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SupplierAcknowledge")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierAcknowledgeBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SupplierAcknowledgeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SupplierReject")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierRejectBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierRejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("TransShipmentAllow")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("YPOMasterID");

                    b.ToTable("ItemPOMaster");
                });

            modelBuilder.Entity("SupplyChainManagement.Models.PRDetails", b =>
                {
                    b.HasOne("SupplyChainManagement.Models.PurchaseRequisition", "PurchaseRequisition")
                        .WithMany()
                        .HasForeignKey("PurchaseRequisitionPRID");

                    b.HasOne("SupplyChainManagement.Models.PurchaseRequisition", null)
                        .WithMany("ItemDetails")
                        .HasForeignKey("PurchaseRequisitionPRID1");

                    b.Navigation("PurchaseRequisition");
                });

            modelBuilder.Entity("SupplyChainManagement.Models.PurchaseRequisition", b =>
                {
                    b.Navigation("ItemDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
